CREATE TABLE IF NOT EXISTS student
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name        VARCHAR NOT NULL,
    last_name         VARCHAR NOT NULL,
    profile_photo_url VARCHAR NOT NULL,
    PRIMARY KEY (id)
);
